$ErrorActionPreference = "SilentlyContinue"

$InstallDir = Split-Path -Parent $PSScriptRoot
$EnvFile = Join-Path $InstallDir ".env"
$ProgramDataRoot = [IO.Path]::GetFullPath($env:ProgramData).TrimEnd('\')
$FallbackDataDir = Join-Path $ProgramDataRoot "AutocomBridge"

function Get-EnvValue {
    param([string]$Name, [string]$Default = "")
    if (-not (Test-Path -LiteralPath $EnvFile)) {
        return $Default
    }
    $Pattern = "^\s*$([regex]::Escape($Name))\s*=\s*(.*)\s*$"
    $Match = Select-String -LiteralPath $EnvFile -Pattern $Pattern | Select-Object -First 1
    if (-not $Match) {
        return $Default
    }
    return $Match.Matches[0].Groups[1].Value.Trim().Trim("'").Trim('"')
}

function Remove-RuntimeDataDirectory {
    param([string]$CandidatePath)
    if ([string]::IsNullOrWhiteSpace($CandidatePath)) {
        return
    }

    $Expanded = [Environment]::ExpandEnvironmentVariables($CandidatePath)
    $FullPath = [IO.Path]::GetFullPath($Expanded).TrimEnd('\')
    $UnderProgramData = $FullPath.StartsWith(
        $ProgramDataRoot + '\',
        [StringComparison]::OrdinalIgnoreCase
    )

    # Never recursively delete ProgramData itself or a custom external folder.
    if (-not $UnderProgramData -or $FullPath -eq $ProgramDataRoot) {
        Write-Warning "Skipping uninstall cleanup outside ProgramData: $FullPath"
        return
    }

    if (Test-Path -LiteralPath $FullPath) {
        Remove-Item -LiteralPath $FullPath -Recurse -Force -ErrorAction SilentlyContinue
    }
}

$ConfiguredDataDir = Get-EnvValue "AUTOCOM_BRIDGE_DATA_DIR" $FallbackDataDir
$KnownRuntimeRoots = @(
    $ConfiguredDataDir,
    (Join-Path $ProgramDataRoot "AutocomBridge"),
    (Join-Path $ProgramDataRoot "DiagnosticEngineConsole"),
    (Join-Path $ProgramDataRoot "DiagonosticEngineConsole")
) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -Unique

foreach ($RuntimeRoot in $KnownRuntimeRoots) {
    Remove-RuntimeDataDirectory -CandidatePath $RuntimeRoot
}

# .env is generated by create_env.ps1 rather than copied as an Inno-owned file.
# Remove it explicitly so that {app} is empty after all installed files are deleted.
Remove-Item -LiteralPath (Join-Path $InstallDir ".env") -Force -ErrorAction SilentlyContinue
